name: "Build Static Website"
description: "Build a static website based on the given Google Sheets document"
author: "Selectstar Safety Research Team"

inputs:
  API_KEY:
    description: "Google API key to use when fetching contents from Google documents"
    required: true
  DATA_URL:
    description: "URL of the Google Sheets document holding the website contents"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "box"
  color: "blue"